default: &default
  adapter: postgresql

development:
  <<: *default
  database: kairan_development

test:
  <<: *default
  database: kairan_test

production:
  <<: *default
  database: kairan_production
